# Generated by Django 4.1.2 on 2022-12-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.model')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('popularity', models.IntegerField(blank=True, default=0, null=True)),
                ('pict_url', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_capacity', models.FloatField(blank=True, null=True)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('kwt_power', models.IntegerField(blank=True, null=True)),
                ('year_start', models.IntegerField(blank=True, null=True)),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('body_length', models.IntegerField(blank=True, null=True)),
                ('body_width', models.IntegerField(blank=True, null=True)),
                ('body_height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('cylinders_order', models.CharField(blank=True, max_length=100, null=True)),
                ('cylinders_number', models.IntegerField(blank=True, null=True)),
                ('torque', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.IntegerField(blank=True, null=True)),
                ('time_to_100', models.FloatField(blank=True, null=True)),
                ('front_brakes', models.CharField(blank=True, max_length=100, null=True)),
                ('back_brakes', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.bodytype')),
                ('drive_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.drivetype')),
                ('engine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.enginetype')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.generation')),
                ('transmission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.transmissiontype')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.country'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('year_start__gte', 1850), ('year_start__lte', 2022)), name='year_start'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('year_end__gte', 1850), ('year_end__lte', 2022)), name='year_end'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('engine_power__gt', 0), ('engine_power__lte', 5000)), name='engine_power'),
        ),
    ]
