# Generated by Django 4.1.2 on 2022-12-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
