# Generated by Django 4.1.2 on 2022-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptions',
            name='name',
        ),
        migrations.AddField(
            model_name='exceptions',
            name='bad_id',
            field=models.IntegerField(null=True),
        ),
    ]
