# Generated by Django 4.1.2 on 2022-12-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.model')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_start_year', models.IntegerField()),
                ('engine_capacity', models.FloatField()),
                ('engine_power', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('body_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.bodytype')),
                ('engine_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.enginetype')),
                ('generation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.generation')),
                ('transmission_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.transmission')),
            ],
        ),
    ]
