# Generated by Django 4.1.2 on 2022-12-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_car_production_start_year_car_engine_power_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='engine_capacity',
        ),
        migrations.AlterField(
            model_name='car',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('engine_power__gt', 0), ('engine_power__lte', 5000)), name='engine_power2'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('engine_type', 5), models.Q(('engine_capacity__gte', 0), ('engine_capacity__lte', 30)), _connector='OR'), name='engine_capacity'),
        ),
    ]
