# Generated by Django 4.1.2 on 2022-12-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_exceptions_name_exceptions_bad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptions',
            name='added',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exceptions',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
    ]
