# Generated by Django 4.1.2 on 2022-12-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_exceptions_added_exceptions_external_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exceptions',
        ),
    ]
