# Generated by Django 4.1.2 on 2022-12-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_engine_capacity_alter_car_popularity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='engine_power2',
        ),
        migrations.AlterField(
            model_name='car',
            name='popularity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
