# Generated by Django 4.1.2 on 2022-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_delete_exceptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(null=True)),
                ('added', models.IntegerField(null=True)),
            ],
        ),
    ]
