# Generated by Django 4.1.2 on 2022-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_brand_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
