# Generated by Django 4.1.2 on 2022-12-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='car',
        ),
        migrations.AddField(
            model_name='favorites',
            name='cars',
            field=models.ManyToManyField(to='cars.car'),
        ),
    ]
