# Generated by Django 4.1.2 on 2022-12-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_engine_capacity_car_engine_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
