# Generated by Django 4.1.2 on 2022-12-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('year_end__gte', 1850), ('year_end__lte', 2022)), name='year_end'),
        ),
    ]
