# Generated by Django 4.1.2 on 2022-12-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_year_end_alter_car_name_car_year_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pict_id',
            field=models.IntegerField(default=0),
        ),
    ]
