# Generated by Django 5.0.6 on 2024-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_trouble_name_alter_trouble_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='resolved',
            field=models.BooleanField(db_column='resolved', default=False),
        ),
    ]
