# Generated by Django 4.1.2 on 2022-12-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_pict_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.car')),
            ],
        ),
    ]
