# Generated by Django 4.1.2 on 2022-12-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_aboba2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboba2',
            name='car',
        ),
        migrations.DeleteModel(
            name='aboba',
        ),
        migrations.DeleteModel(
            name='aboba2',
        ),
    ]
