# Generated by Django 4.1.2 on 2022-12-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_car_back_brakes_car_body_height_car_body_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.enginetype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='pict_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='popularity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.transmissiontype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_start',
            field=models.IntegerField(null=True),
        ),
    ]
